package com.example.baseproject.utils.enumz

enum class SketchEffect {
    ORIGINAL_TO_GRAY,
    ORIGINAL_TO_SKETCH,
    ORIGINAL_TO_COLORED_SKETCH,
    ORIGINAL_TO_SOFT_SKETCH,
    ORIGINAL_TO_SOFT_COLOR_SKETCH,
    GRAY_TO_SKETCH,
    GRAY_TO_COLORED_SKETCH,
    GRAY_TO_SOFT_SKETCH,
    GRAY_TO_SOFT_COLOR_SKETCH,
    SKETCH_TO_COLORED_SKETCH,
    STROKE_ONLY
}